# Spring Boot
server:
  port: 8060
  servlet:
    context-path: /mcp-server-v1

spring:
  application:
    name: mcp-server-v1
  # R2DBC Datasource Configuration
  r2dbc:
    url: r2dbc:h2:mem:///testdb-v1;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    mcp:
      server:
        name: "mcp-server-v1"
        description: "MCP Server V1 with Person Tools"
        version: "1.0.0"
        transport-type: sse # Use sse for reactive transport
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    com.nacos.mcp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 