server:
  port: 8070

spring:
  application:
    name: mcp-client
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  ai:
    deepseek:
      api-key: "sk-c82a3957785d4c48b08a62e0e707ecf2"
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        enabled: true
        name: mcp-client-app
        version: 1.0.0
        type: SYNC
        request-timeout: 30s
        sse:
          connections:
            router:
              url: http://localhost:8050
              sse-endpoint: /sse

logging:
  level:
    org.springframework.ai: DEBUG
    com.nacos.mcp.client: DEBUG
    org.springframework.ai.mcp: DEBUG
    com.nacos.mcp: DEBUG
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info 