spring:
  ai:
    deepseek:
      api-key: "sk-c82a3957785d4c48b08a62e0e707ecf2"
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: deepseek-chat
    
    # 暂时禁用MCP客户端，避免连接问题
    mcp:
      client:
        enabled: false
        # sse:
        #   connections:
        #     nacos-mcp-router:
        #       url: http://localhost:8050/mcp/jsonrpc
        #       request-timeout: 30s
        #       transport: sse

logging:
  level:
    org.springframework.ai: DEBUG
    com.nacos.mcp.client: DEBUG
    org.springframework.ai.mcp: DEBUG

server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: health,info 