server:
  port: 8070

spring:
  application:
    name: mcp-client
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  ai:
    deepseek:
      api-key: "sk-c82a3957785d4c48b08a62e0e707ecf2"
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: deepseek-chat

logging:
  level:
    org.springframework.ai: DEBUG
    com.nacos.mcp.client: DEBUG
    org.springframework.ai.mcp: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info 