# Example configuration for Nacos MCP Router Spring
# Copy this file to src/main/resources/application.yml and modify as needed

spring:
  application:
    name: nacos-mcp-router-spring
  profiles:
    active: dev
  # Spring AI Configuration
  ai:
    openai:
      # Get your API key from https://platform.openai.com/api-keys
      api-key: ${OPENAI_API_KEY:sk-your-openai-api-key-here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-ada-002

server:
  port: ${PORT:8000}
  servlet:
    context-path: /

# Nacos Configuration
nacos:
  addr: ${NACOS_ADDR:127.0.0.1:8848}
  username: ${NACOS_USERNAME:nacos}
  password: ${NACOS_PASSWORD:nacos}
  namespace: ${NACOS_NAMESPACE:public}

# MCP Router Configuration
mcp:
  router:
    # Working mode: "router" for intelligent routing, "proxy" for single server proxy
    mode: ${MODE:router}
    # Transport type: stdio, sse, streamable_http
    transport-type: ${TRANSPORT_TYPE:stdio}
    # Only used in proxy mode - name of the MCP server to proxy to
    proxied-mcp-name: ${PROXIED_MCP_NAME:}
    # Compass registry configuration
    compass:
      api-base: ${COMPASS_API_BASE:https://registry.mcphub.io}
    # Search configuration
    search:
      # Minimum similarity score for search results (0.0 to 1.0)
      min-similarity: ${SEARCH_MIN_SIMILARITY:0.5}
      # Maximum number of search results to return
      result-limit: ${SEARCH_RESULT_LIMIT:10}

# Logging Configuration
logging:
  level:
    root: INFO
    com.nacos: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/nacos-mcp-router.log

# Management Configuration (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true

# Application Info
info:
  app:
    name: Nacos MCP Router Spring
    description: A Spring Boot application for MCP server routing and proxy
    version: 1.0.0
    author: nacos-mcp-router-spring

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true

logging:
  level:
    com.nacos: DEBUG
    org.springframework.ai: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.nacos: INFO
  file:
    name: /var/log/nacos-mcp-router/application.log 