# Spring Boot
server:
  port: 8061
  servlet:
    context-path: /mcp-server-v2

spring:
  application:
    name: mcp-server-v2
  # R2DBC Datasource Configuration
  r2dbc:
    url: r2dbc:h2:mem:///testdb-v2;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    mcp:
      server:
        name: "mcp-server-v2"
        description: "MCP Server V2 with Person Tools"
        version: "1.0.0"
        transport-type: sse # Use sse for reactive transport
        enabled: true
        tools: >
          [
            {
              "name": "getAllPersons",
              "description": "Get all persons from the database.",
              "javaFunctionName": "com.nacos.mcp.server.v2.tools.PersonQueryTools.getAllPersons"
            },
            {
              "name": "addPerson",
              "description": "Add a new person to the database.",
              "javaFunctionName": "com.nacos.mcp.server.v2.tools.PersonModifyTools.addPerson"
            }
          ]
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    com.nacos.mcp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 