spring:
  application:
    name: mcp-router
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  main:
    banner-mode: "off"
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    default-property-inclusion: NON_NULL
    deserialization:
        fail-on-unknown-properties: false
        accept-single-value-as-array: true

server:
  port: 8050
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

nacos:
  discovery:
    server-addr: localhost:8848
    namespace: public
  config:
    server-addr: "localhost:8848"
    namespace: "public"
    group: "DEFAULT_GROUP"
    username: nacos
    password: nacos
    file-extension: yml
    
mcp:
  router:
    discovery:
      refresh-interval: 30000
      health-check-interval: 15000
      health-check-timeout: 5000
    connection:
      max-connections-per-server: 10
      connect-timeout: 10000
      read-timeout: 30000
      pool:
        max-idle: 5
        min-idle: 1
        max-active: 20
    routing:
      load-balancer: "round-robin"
      sticky-sessions: false
      failover:
        enabled: true
        max-retries: 2
        retry-delay: 1000
    tools:
      max-execution-time: 60000
      caching:
        enabled: true
        ttl: 300000
        max-size: 1000
    resources:
      max-size: 10485760
      allowed-types:
        - "text/*"
        - "application/json"
        - "application/xml"
        - "application/yaml"
      caching:
        enabled: true
        ttl: 600000
    prompts:
      max-length: 32768
      caching:
        enabled: true
        ttl: 3600000

logging:
  level:
    com.nacos.mcp.router: INFO
    org.springframework.ai: DEBUG
    com.alibaba.nacos: WARN
    reactor.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
  file:
    name: "logs/nacos-mcp-router.log"
    max-size: "10MB"
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,loggers"
      base-path: "/actuator"
  endpoint:
    health:
      show-details: "when-authorized"
      show-components: "always"
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: "${spring.application.name}"

spring.ai:
  deepseek:
    chat:
      api-key: "sk-c82a3957785d4c48b08a62e0e707ecf2"
      options:
        model: deepseek-chat # Or another model like deepseek-coder

